config/routes.rb
Fridgematch::Application.routes.draw do
  resources :ingredient_categories

  resources :recipes, only: :index

  resources :ingredients, except: :edit do
    get :autocomplete_ingredient_name, on: :collection
    collection do
      get :new_blacklisted
      post :create_blacklisted
    end
    member do
      delete :destroy_blacklisted
    end
  end
  root to: "recipes#index"

  resources :nutritional_values

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many :blacklisted_users, class_name: "User", join_table: "blacklisted_ingredients_users"
  has_and_belongs_to_many :users
  has_and_belongs_to_many :recipes
  belongs_to :ingredient_category
  has_many :nutritional_values

  validates :name, presence: true, uniqueness: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  expose(:ingredients) { current_user.ingredients }
  expose(:ingredient, attributes: :ingredient_params)
  expose(:blacklisted_ingredients) { current_user.blacklisted_ingredients }
  expose(:blacklisted_ingredient){ blacklisted_ingredients.find(params[:id]) } 

  autocomplete :ingredient, :name, full: true

  def index
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
    current_user.ingredients.delete(ingredient)
    flash[:notice] = "Ingredient deleted!"
    render action: :index
  end

  def show
  end

  def create
    self.ingredient = Ingredient.find_or_create_by(ingredient_params)
    binding.pry
    if ingredient.save
      current_user.ingredients << ingredient
      flash[:notice] = "Ingredient added!"
      redirect_to action: :index
    else
      render :new
    end
  end

  def new_blacklisted
    self.blacklisted_ingredient = Ingredient.new
  end

  def create_blacklisted
    self.blacklisted_ingredient = Ingredient.find_or_create_by(ingredient_params)
    if blacklisted_ingredient.save
      current_user.blacklisted_ingredients << blacklisted_ingredient
      flash[:notice] = "Blacklisted Ingredient added!"
      redirect_to action: :index
    else
      render :new
    end
  end
  def destroy_blacklisted
    current_user.blacklisted_ingredients.delete(blacklisted_ingredient)
    flash[:notice] = "Blacklisted Ingredient deleted!"
    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_blacklisted_form.haml
= simple_form_for(blacklisted_ingredient, url: create_blacklisted_ingredients_path ) do |f|
  - if blacklisted_ingredient.errors.any?
    .error_explanation
      %ul
      - blacklisted_ingredient.errors.full_messages.each do |msg|
        %li= msg
  .form-group
    = f.input :name, :url => autocomplete_ingredient_name_ingredients_path, as: :autocomplete, input_html: { class: 'form-control' }

  .actions
    = f.submit "Create blacklisted ingredient", class: "btn btn-success"

app/views/ingredients/_form.html.haml
= simple_form_for(ingredient) do |f|
  - if ingredient.errors.any?
    .error_explanation
      %ul
      - ingredient.errors.full_messages.each do |msg|
        %li= msg
  .form-group
    = f.input :name, :url => autocomplete_ingredient_name_ingredients_path, as: :autocomplete, input_html: { class: 'form-control' }

  .actions
    = f.submit class: "btn btn-success"

app/views/ingredients/edit.html.haml
%h1 Editing ingredient

= render 'form'

= link_to 'Show', ingredient
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1 Your ingredients

%table.table
  %thead
    %tr
      %th Delete
      %th Name
    %tbody
    - ingredients.each do |ingredient|
      %tr
        %td
          = link_to ingredient, method: :delete, data: { confirm: 'Are you sure?' } do
            .glyphicon.glyphicon-remove-sign
        %td= ingredient.name

%br
= link_to 'Add Ingredient', new_ingredient_path, class: "btn btn-default"

%h1 Your blacklisted ingredients

%table.table
  %thead
    %tr
      %th Delete
      %th Name
    %tbody
    - blacklisted_ingredients.each do |blacklisted|
      %tr
        %td
          = link_to destroy_blacklisted_ingredient_path(blacklisted), method: :delete, data: { confirm: 'Are you sure?' } do
            .glyphicon.glyphicon-remove-sign
        %td= blacklisted.name

%br

= link_to 'Add Blacklisted Ingredient', new_blacklisted_ingredients_path, class: "btn btn-default"

%br
%br

app/views/ingredients/new.html.haml
.col-sm-6
  %h1 New ingredient

  = render 'form'

  %br
  = link_to 'Back', ingredients_path

app/views/ingredients/new_blacklisted.html.haml
.col-sm-6
  %h1 New blakclisted ingredient

  = render 'blacklisted_form'

  %br
  = link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%p#notice= notice

= ingredient.name

= link_to 'Back', ingredients_path