config/routes.rb
Fridgematch::Application.routes.draw do
  resources :ingredient_categories

  resources :recipes, only: :index

  resources :ingredients, except: :edit do
    get :autocomplete_ingredient_name, on: :collection
    collection do
      get :new_blacklisted
      post :create_blacklisted
    end
    member do
      delete :destroy_blacklisted
    end
  end
  root to: "recipes#index"

  resources :nutritional_values

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)

end

app/models/ingredient_category.rb
class IngredientCategory < ActiveRecord::Base

  has_many :ingredients

end

app/controllers/ingredient_categories_controller.rb
class IngredientCategoriesController < ApplicationController
  before_action :set_ingredient_category, only: [:show, :edit, :update, :destroy]

  # GET /ingredient_categories
  # GET /ingredient_categories.json
  def index
    @ingredient_categories = IngredientCategory.all
  end

  # GET /ingredient_categories/1
  # GET /ingredient_categories/1.json
  def show
  end

  # GET /ingredient_categories/new
  def new
    @ingredient_category = IngredientCategory.new
  end

  # GET /ingredient_categories/1/edit
  def edit
  end

  # POST /ingredient_categories
  # POST /ingredient_categories.json
  def create
    @ingredient_category = IngredientCategory.new(ingredient_category_params)

    respond_to do |format|
      if @ingredient_category.save
        format.html { redirect_to @ingredient_category, notice: 'Ingredient category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ingredient_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @ingredient_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredient_categories/1
  # PATCH/PUT /ingredient_categories/1.json
  def update
    respond_to do |format|
      if @ingredient_category.update(ingredient_category_params)
        format.html { redirect_to @ingredient_category, notice: 'Ingredient category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ingredient_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredient_categories/1
  # DELETE /ingredient_categories/1.json
  def destroy
    @ingredient_category.destroy
    respond_to do |format|
      format.html { redirect_to ingredient_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient_category
      @ingredient_category = IngredientCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_category_params
      params[:ingredient_category]
    end
end

app/helpers/ingredient_categories_helper.rb
module IngredientCategoriesHelper
end

app/views/ingredient_categories/_form.html.erb
<%= form_for(@ingredient_category) do |f| %>
  <% if @ingredient_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient_category.errors.count, "error") %> prohibited this ingredient_category from being saved:</h2>

      <ul>
      <% @ingredient_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredient_categories/edit.html.erb
<h1>Editing ingredient_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient_category %> |
<%= link_to 'Back', ingredient_categories_path %>

app/views/ingredient_categories/index.html.erb
<h1>Listing ingredient_categories</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredient_categories.each do |ingredient_category| %>
      <tr>
        <td><%= link_to 'Show', ingredient_category %></td>
        <td><%= link_to 'Edit', edit_ingredient_category_path(ingredient_category) %></td>
        <td><%= link_to 'Destroy', ingredient_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient category', new_ingredient_category_path %>

app/views/ingredient_categories/new.html.erb
<h1>New ingredient_category</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredient_categories_path %>

app/views/ingredient_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ingredient_category_path(@ingredient_category) %> |
<%= link_to 'Back', ingredient_categories_path %>