config/routes.rb
Fridgematch::Application.routes.draw do
  resources :ingredient_categories

  resources :recipes, only: :index

  resources :ingredients, except: :edit do
    get :autocomplete_ingredient_name, on: :collection
    collection do
      get :new_blacklisted
      post :create_blacklisted
    end
    member do
      delete :destroy_blacklisted
    end
  end
  root to: "recipes#index"

  resources :nutritional_values

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to root_path, class: "navbar-brand" do
  FridgeMatch
%ul.nav.navbar-nav.pull-right
  - if user_signed_in?
    %li
      .welcome  
        Hello 
        = current_user.email
        - if current_user.admin
          = link_to "Admin", admin_root_path, class: "btn btn-primary btn-xs"
    %li= link_to "Ingredients", ingredients_path
    %li= link_to "Recipes", recipes_path
    %li= link_to "Recipes", recipes_path
    %li= link_to "Sign out", destroy_user_session_path, method: :delete
  - else
    %li= link_to "Sign in", new_user_session_path
    %li= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Fridgematch"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{class: "#{controller_name} #{action_name}"}
    .navbar.navbar-default
      .container-fluid
        = render 'layouts/navigation'
    #main{role: "main"}
      .container-fluid
        .content
          .span12
            = render 'layouts/messages'
            = yield
          %footer